### ISSUE TITLE
Error: TypeError: obj.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by jonnybarnes** [pa11y/pa11y-dashboard#119]
Using Node 6.0.0 on Debian, here’s the full output:

``` shell
$ NODE_ENV=production node index.js
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0

pa11y-dashboard started
mode: production
uri:  http://:::4000
(node:2615) DeprecationWarning: sys is deprecated. Use util instead.

pa11y-webservice started
mode: production
uri:  http://0.0.0.0:3000
/home/jonny/websites/pa11y-dashboard/node_modules/hoek/lib/index.js:47
        if (obj.hasOwnProperty(i)) {
                ^

TypeError: obj.hasOwnProperty is not a function
    at Object.exports.clone (/home/jonny/websites/pa11y-dashboard/node_modules/hoek/lib/index.js:47:17)
    at processConfig (/home/jonny/websites/pa11y-dashboard/node_modules/joi/lib/index.js:57:39)
    at Object.exports.validate (/home/jonny/websites/pa11y-dashboard/node_modules/joi/lib/index.js:121:5)
    at exports.query (/home/jonny/websites/pa11y-dashboard/node_modules/hapi/lib/validation.js:16:21)
    at /home/jonny/websites/pa11y-dashboard/node_modules/hapi/lib/request.js:300:13
    at iterate (/home/jonny/websites/pa11y-dashboard/node_modules/async/lib/async.js:134:13)
    at /home/jonny/websites/pa11y-dashboard/node_modules/async/lib/async.js:145:25
    at /home/jonny/websites/pa11y-dashboard/node_modules/hoek/lib/index.js:585:22
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by rowanmanning** [comment]
Hi @jonnybarnes! Sorry I somehow missed this. I'll look into it as soon as possible :)

**Comment by rowanmanning** [comment]
I completely forgot: currently the dashboard only supports Node.js `0.10`, which is why you're getting errors with `6.0`. This is a known issue and we'd like to get it sorted but it's a considerable amount of work to upgrade. Sorry for the confusion, perhaps it's not clear enough in the docs which Node.js versions we support.
