### ISSUE TITLE
Configs not loaded & 500 error

### ISSUE THREAD

**Issue by petervangennip** [pa11y/pa11y-dashboard#229]
I am trying to setup a dashboard but I keep hitting a wall. I checked this repo's issues but couldn't find a proper solution.

Windows 10
Node v8.9.4
MongoDB is running on localhost:27017

Error in dashboard on http://127.0.0.1:4000/
```
Stack-Trace
Error: connect EADDRNOTAVAIL 0.0.0.0:4000  
at Object.exports._errnoException (util.js:870:11)
at exports._exceptionWithHostPort (util.js:893:20)
at TCPConnectWrap.afterConnect as oncomplete
```
My development.json looks like this: 
```
{
	"port": 4000,
	"noindex": true,
	"readonly": false,
	"webservice": {
		"database": "mongodb://localhost/pa11y-webservice-dev",
		"host": "127.0.0.1",
		"port": 3000,
		"cron": "0 30 0 * * *"
	}
}
```

However, when running index.js I get this (the uri is not updated to 127.0.0.1)

```
Pa11y Dashboard started
mode: development 
uri:  http://:::4000

Pa11y Webservice started
mode: development 
uri:  http://0.0.0.0:3000
```

Any ideas or suggestions?

**Comment by petervangennip** [comment]
Solved. What worked for me:
- switched to node v10.12.0
- removed node_modules
- re-installed all modules (npm i)
