### ISSUE TITLE
Error 500 on fresh install and startup

### ISSUE THREAD

**Issue by pandabrand** [pa11y/pa11y-dashboard#252]
This issue is similar to [229](https://github.com/pa11y/pa11y-dashboard/issues/229) however, unless node v10 isn't supported anymore its not the same. 
OS X 10.14.6
node: 10.17.0
MongoDB is running

I've checked out the latest version of the dashboard. copied the dev config and start with `NODE_ENV=developement node index.js`

This returns:
``` 
Pa11y Dashboard started
mode: development
uri:  http://:::4000
Server running at: http://0.0.0.0:3000

Pa11y Webservice started
mode:     development
uri:      http://0.0.0.0:3000
database: mongodb://localhost/pa11y-webservice-dev
cron:     0 30 0 * * *
```
and then I have the Eeek! 500 error page. 
Any insight would be fantastic thanks.

**Comment by pandabrand** [comment]
I tried running this under different node versions with nodenv and get the same error in v8 and v13

**Comment by pandabrand** [comment]
Updating to OS X 10.15.2 fixed this.

**Comment by pandabrand** [comment]
Ok, so this didn't fix this and I'm at a loss as to how to figure what's wrong. 
I've tried different versions of node[10.17.0, 12.13.1, 13.2.0] and I still get the same error.

```
Error: Error 404
    at Request._callback (/Volumes/HAL/Work/blueshoon/pa11y/pa11y-dashboard/node_modules/pa11y-webservice-client-node/lib/client.js:127:16)
    at Request.self.callback (/Volumes/HAL/Work/blueshoon/pa11y/pa11y-dashboard/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/Volumes/HAL/Work/blueshoon/pa11y/pa11y-dashboard/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/Volumes/HAL/Work/blueshoon/pa11y/pa11y-dashboard/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1200:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I did a little digging and specifically its failing on trying to call `http://0.0.0.0:3000/tasks` is this because my dashboard uri is wrong? If so, why isn it not starting correctly? Again if anyone has any idea of what's happening that would be great.

**Comment by pandabrand** [comment]
Sorry to be clogging up the issue with my silliness but figured it out. There was a docker container that another service started on port 3000.
