### ISSUE TITLE
ObjectID generation failed

### ISSUE THREAD

**Issue by pentiafrn** [pa11y/pa11y-dashboard#260]
I have pa11y dashboard running as a docker image in Microsoft Azure and after a couple of days it breaks the MongoDB database and give the following error:

`appsvctmp/volatile/logs/runtime/03b8c0df25b5bbc05a47fc970cfdf3378bda0f6a83b93fb466e639170461f854.log
2020-05-11T12:57:56.635985138Z: [ERROR] at endReadableNT (_stream_readable.js:1143:12)
2020-05-11T12:57:56.635994939Z: [ERROR] at process._tickCallback (internal/process/next_tick.js:63:19)
2020-05-11T12:57:57.210538386Z: [ERROR] ObjectID generation failed. Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
2020-05-11T13:02:24.271164967Z: [ERROR]
2020-05-11T13:02:24.272561403Z: [ERROR] Error: socket hang up
2020-05-11T13:02:24.273194219Z: [ERROR] at createHangUpError (_http_client.js:323:15)
2020-05-11T13:02:24.273214120Z: [ERROR] at Socket.socketOnEnd (_http_client.js:426:23)
2020-05-11T13:02:24.273224020Z: [ERROR] at Socket.emit (events.js:203:15)
2020-05-11T13:02:24.273245420Z: [ERROR] at endReadableNT (_stream_readable.js:1143:12)
2020-05-11T13:02:24.273255421Z: [ERROR] at process._tickCallback (internal/process/next_tick.js:63:19)`

I tried deleting the corrupt MongoDB collection and starting again, but it still keeps breaking after a couple of days. It is only the "results"-collection that seems to break. The "tasks" is not affected by the bug.

Running with the following options:

`{
    "port": 80,
    "webservice": {
        "database": "'$WEBSERVICE_DATABASE'",
        "host": "0.0.0.0",
        "port": 3000,
        "cron": "0 30 0 * * *",
        "chromeLaunchConfig": {
            "ignoreHTTPSErrors": true,
            "headless": true,
            "args": [
                "--no-sandbox"
            ]
        }
    }
}`

And running version: 3.1.0.

Any help would be appreciated.

**Comment by EHLOVader** [comment]
I'm running v 4.2.0 and still getting this. Looking through change logs it appears that there should have been a fix to this already.
