### ISSUE TITLE
Just how to get this working?

### ISSUE THREAD

**Issue by knkarthik** [pa11y/pa11y-dashboard#271]
On Mac 10.15.6. I've installed mongodb from [homebrew](https://github.com/mongodb/homebrew-brew). Followed the setup guide and used this config:

```
{
        "port": 4000,
        "noindex": true,
        "readonly": false,

        "webservice": {
                "database": "mongodb://127.0.0.1:27017/pa11y-webservice",
                "host": "0.0.0.0",
                "port": 3000,
                "cron": "0 30 0 * * *"
        }
}
```
and this is what I'm getting:

```
$NODE_ENV=development node index.js

Pa11y Dashboard started
mode: development
uri:  http://:::4000
Server running at: http://0.0.0.0:3000

Pa11y Webservice started
mode:     development
uri:      http://0.0.0.0:3000
database: mongodb://127.0.0.1:27017/pa11y-webservice
cron:     0 30 0 * * *
(node:95310) UnhandledPromiseRejectionWarning: MongoError: w has to be a non-negative number and not greater than 50
    at Function.MongoError.create (/Users/kneelakandan/dev/pa11y-dashboard/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/kneelakandan/dev/pa11y-dashboard/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/Users/kneelakandan/dev/pa11y-dashboard/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/Users/kneelakandan/dev/pa11y-dashboard/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/Users/kneelakandan/dev/pa11y-dashboard/node_modules/mongodb-core/lib/connection/connection.js:333:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:95310) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:95310) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:95310) UnhandledPromiseRejectionWarning: MongoError: w has to be a non-negative number and not greater than 50
    at Function.MongoError.create (/Users/kneelakandan/dev/pa11y-dashboard/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/kneelakandan/dev/pa11y-dashboard/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/Users/kneelakandan/dev/pa11y-dashboard/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/Users/kneelakandan/dev/pa11y-dashboard/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/Users/kneelakandan/dev/pa11y-dashboard/node_modules/mongodb-core/lib/connection/connection.js:333:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:95310) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

I still can access the UI, so added a URL, tried to run tests and then I get this:

```
Starting to run one-off task @ Tue Oct 20 2020 10:54:19 GMT-0400 (Eastern Daylight Time)
Starting task 5f8ef7b581ff24744f2e0a12
[5f8ef7b581ff24744f2e0a12]  > Running Pa11y on URL https://www.github.com/
[5f8ef7b581ff24744f2e0a12]  > Launching Headless Chrome
model:task:runById failed, with id: 5f8ef7b581ff24744f2e0a12
Pa11y timed out (1000ms)
Failed to finish task 5f8ef7b581ff24744f2e0a12
ObjectID generation failed. Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
[5f8ef7b581ff24744f2e0a12]  > Opening URL in Headless Chrome
[5f8ef7b581ff24744f2e0a12]  > Browser Console: JQMIGRATE: Migrate is installed, version 1.4.1
[5f8ef7b581ff24744f2e0a12]  > Browser Console: [Facebook Pixel] - Duplicate Pixel ID: 2197461077246231.
```

**Comment by danieldid** [comment]
@knkarthik did you figure it out? I'm currently facing the same issue on my server running Ubuntu 18.04 LTS.

Changing the port in config.js to anything greater than 3000 brings the same result as you described:
```
'use strict';

const fs = require('fs');
const environment = (process.env.NODE_ENV || 'development');
const jsonPath = `./config/${environment}.json`;
const jsPath = `./config/${environment}.js`;

if (fs.existsSync(jsonPath)) {
	module.exports = require(jsonPath);
} else if (fs.existsSync(jsPath)) {
	module.exports = require(jsPath);
} else {
	module.exports = {
		port: Number(env('PORT', '5000')),
		noindex: env('NOINDEX', 'true') === 'true',
		readonly: env('READONLY', 'false') === 'true',

		webservice: env('WEBSERVICE_URL', {
			database: env('WEBSERVICE_DATABASE', 'mongodb://localhost/pa11y-webservice'),
			host: env('WEBSERVICE_HOST', '0.0.0.0'),
			port: Number(env('WEBSERVICE_PORT', '50001')),
			cron: env('WEBSERVICE_CRON', false)
		})
	};
}

function env(name, defaultValue) {
	const value = process.env[name];
	return typeof value === 'string' ? value : defaultValue;
}
```

Steps to reproduce:
- Checking out the repo
- install dependencies
- install mongodb (https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/)
- change ports (5000 and 5001)
- runs into troubles with same results as https://github.com/pa11y/pa11y-dashboard/issues/271#issue-725675888

**Comment by josebolos** [comment]
Hi all,

Could you please run these two commands and let me know the result, so I can see what versions are you using?

Pa11y environment (from your pa11y-dashboard clone):
```
./node_modules/.bin/pa11y -n
```

MongoDB version:
```
brew info mongodb-community
```

Thanks!

**Comment by danieldid** [comment]
Hi @josebolos, 

I used the mongodb installation manual from here (https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/). It's version 4.4 right now.

For pa11y:
```
./node_modules/.bin/pa11y -n
Pa11y:      5.3.0
Node.js:    12.20.1
npm:        7.5.2
OS:         4.15.0-112-generic (linux)
```

For mongodb:
```
mongod --version
db version v4.4.3
Build Info: {
    "version": "4.4.3",
    "gitVersion": "913d6b62acfbb344dde1b116f4161360acd8fd13",
    "openSSLVersion": "OpenSSL 1.1.1  11 Sep 2018",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "ubuntu1804",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}
```


![versions](https://user-images.githubusercontent.com/4113271/107550436-53036380-6bd1-11eb-85cb-3ddb521d3405.png)


My `config.js` file looks like this:
```
'use strict';

const fs = require('fs');
const environment = (process.env.NODE_ENV || 'development');
const jsonPath = `./config/${environment}.json`;
const jsPath = `./config/${environment}.js`;

if (fs.existsSync(jsonPath)) {
        module.exports = require(jsonPath);
} else if (fs.existsSync(jsPath)) {
        module.exports = require(jsPath);
} else {
        module.exports = {
                port: Number(env('PORT', '5050')),
                noindex: env('NOINDEX', 'true') === 'true',
                readonly: env('READONLY', 'false') === 'true',

                webservice: env('WEBSERVICE_URL', {
                        database: env('WEBSERVICE_DATABASE', 'mongodb://localhost/pa11y-webservice'),
                        host: env('WEBSERVICE_HOST', '0.0.0.0'),
                        port: Number(env('WEBSERVICE_PORT', '5001')),
                        cron: env('WEBSERVICE_CRON', false)
                })
        };
}

function env(name, defaultValue) {
        const value = process.env[name];
        return typeof value === 'string' ? value : defaultValue;
}
```

**Comment by SiweiZhang14** [comment]
Hi @knkarthik did you figure it out? I've got the same errors as yours. Please let me know how you fixed it. Thank you so much!

**Comment by knkarthik** [comment]
@josebolos 

```
Pa11y:      5.3.0
Node.js:    12.21.0
npm:        6.14.11
OS:         4.19.121-linuxkit (linux)
mongo: db version v4.4.3
```
@SiweiZhang14 Sorry, didn't figure it out yet.

**Comment by pobtastic** [comment]
That's a red herring, it works fine for us still with those warnings;

```
$ docker logs xxxxx-pa11y

Pa11y Dashboard started
mode: production
uri:  http://:::4000
Server running at: http://0.0.0.0:3000

Pa11y Webservice started
mode:     production
uri:      http://0.0.0.0:3000
database: mongodb://mongo:27017/pa11y
cron:     0 30 0 * * *
(node:1) UnhandledPromiseRejectionWarning: MongoError: w has to be a non-negative number and not greater than 50
    at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
    at /app/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/app/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/app/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:333:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1) UnhandledPromiseRejectionWarning: MongoError: w has to be a non-negative number and not greater than 50
    at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
    at /app/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/app/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/app/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:333:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

Starting to run one-off task @ 2021-03-25T15:50:26.977Z
Starting task 605cae9159c44f7188d4f25f
[605cae9159c44f7188d4f25f]  > Running Pa11y on URL http://webserver
[605cae9159c44f7188d4f25f]  > Launching Headless Chrome
[605cae9159c44f7188d4f25f]  > Opening URL in Headless Chrome
[605cae9159c44f7188d4f25f]  > Loading runner: htmlcs
[605cae9159c44f7188d4f25f]  > Injecting Pa11y
[605cae9159c44f7188d4f25f]  > Injecting runner: htmlcs
[605cae9159c44f7188d4f25f]  > Running Pa11y on the page
[605cae9159c44f7188d4f25f]  > Document title: "XXXXX | Homepage"
Finished task 605cae9159c44f7188d4f25f
Finished running one-off task @ 2021-03-25T15:50:56.969Z
```

I'd say it looks like your headless Chrome isn't set up correctly?  It's either not responding at all, or not letting pa11y know when it's done?  Or ... this is a WordPress site I assume?  Maybe you're just not waiting long enough for it to list out all the information.

**Comment by josebolos** [comment]
Hi all,

@pobtastic is correct, there are a lot of messages posted there, but most of them are not errors at all, so it's difficult to understand what is going on exactly.

For the record, Pa11y Dashboard currently uses version 2.2 of the MongoDB driver, which means that only MongoDB servers of versions **3.4 or older** are supported: [https://docs.mongodb.com/drivers/node/compatibility/](https://docs.mongodb.com/drivers/node/compatibility/). Those of you using versions of MongoDB more recent than that, there's a good chance this is the cause of the behaviour that you're experiencing.

An upgrade to a more recent version of the Node.js MongoDB driver is in the roadmap for v4 of Pa11y Dashboard, but we don't have a timeline for it yet as this project is exclusively run by volunteers in their spare time.

To those of you experiencing problems, please try to run Dashboard using an older version of MongoDB. Please do also check for authentication issues with MongoDB. MongoDB's authentication can be enabled or disabled, and if enabled you may have to manually create a user and database before Pa11y Dashboard can make use of it.

I'm closing this issue now. If you are still experiencing any problems when using MongoDB 3.4 or older, please create a new issue including the versions of Node and MongoDB in use and, more importantly, a copy of the configuration file being used, and I will have a look at it. 

Thanks!
