### ISSUE TITLE
Error [MongoError]: w has to be a non-negative number and not greater than 50

### ISSUE THREAD

**Issue by santoshdasa12345** [pa11y/pa11y-dashboard#275]
Hi, I have entered NODE_ENV=development node index.js
I got the following error

Pa11y Dashboard started
mode: development
uri:  http://:::4000
Server running at: http://0.0.0.0:3000

Pa11y Webservice started
mode:     development
uri:      http://0.0.0.0:3000
database: mongodb://localhost/pa11y-webservice
cron:     0 30 0 * * *

/Users/santoshdasari/Desktop/pa11y/pa11y-dashboard/node_modules/mongodb-core/lib/error.js:31
    err = new MongoError(options.message || options.errmsg || options.$err || "n/a");
          ^
Error [MongoError]: w has to be a non-negative number and not greater than 50
    at Function.MongoError.create (/Users/santoshdasari/Desktop/pa11y/pa11y-dashboard/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/santoshdasari/Desktop/pa11y/pa11y-dashboard/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/Users/santoshdasari/Desktop/pa11y/pa11y-dashboard/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/Users/santoshdasari/Desktop/pa11y/pa11y-dashboard/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/Users/santoshdasari/Desktop/pa11y/pa11y-dashboard/node_modules/mongodb-core/lib/connection/connection.js:333:22)
    at Socket.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  ok: 0,
  errmsg: 'w has to be a non-negative number and not greater than 50',
  code: 9,
  codeName: 'FailedToParse'
}

Additional info
OS: MacOSCatalina
Mongodb: mongodb-community@4.4
Node:v15.12.0
Could you help to fix this issue

**Comment by an-snatcher** [comment]
I am facing same issue ass well. Can anyone help on this?

**Comment by danieldid** [comment]
There is already an open issue. Check this out #271

**Comment by josebolos** [comment]
Hi all,

As I've just mentioned in https://github.com/pa11y/pa11y-dashboard/issues/271#issuecomment-815920247 Pa11y Dashboard currently uses version 2.2 of the MongoDB driver, which means that only MongoDB servers of versions **3.4 or older** are supported: [https://docs.mongodb.com/drivers/node/compatibility/](https://docs.mongodb.com/drivers/node/compatibility/).

Please try to run Dashboard using an older version of MongoDB and if you are still experiencing any problems when using MongoDB 3.4 or older, please create a new issue including the versions of Node and MongoDB in use and, more importantly, a copy of the configuration file being used, and I will have a look at it. 

Thanks!
